import { Link } from 'react-router-dom';

import { OM_CONTACT } from './content.js';
const LEGAL={privacy:{title:'Privacy Policy',intro:'This policy explains what OM Stationary collects when you use this website, and what we do with it.',sections:[['What we collect','We collect your name, mobile number, email address, delivery addresses, order details and payment status. We never ask for and never store card numbers, CVV, UPI PIN or any payment password.'],['Why we collect it','We use your details to process orders, deliver products, issue invoices, provide order updates and support you after delivery.'],['How long we keep it','We keep your order and invoice records for as long as needed for accounting and after-sales support. You can ask us to delete your account at any time.'],['Who we share it with','We do not sell your personal data. We share only what is strictly necessary with the delivery partner handling your order.'],['Your choices','You can view and edit your profile, addresses and order history from your account, and you can ask us to correct or delete your information.']]},terms:{title:'Terms & Conditions',intro:'These terms govern your use of the OM Stationary website and the orders you place through it.',sections:[['About us','OM Stationary is an independent retailer operating from G5JF+784, Ambedkar Rd, Sohgi, Patna, Bihar 800007.'],['Orders','An order is accepted only after the store confirms it. We may cancel an order if an item is unavailable or an obvious pricing error is found, and we will refund any amount collected.'],['Pricing','Prices include all charges shown at checkout. Prices and stock can change, and the price at the time your order is accepted is the price that applies.'],['Delivery','Delivery is available in configured PIN codes. Delivery is attempted during business hours. Risk and title pass to you on delivery.'],['Pickup','Pickup orders must be collected within the requested window. Uncollected orders may be cancelled and refunded.'],['Liability','We are responsible for delivering the goods described on your invoice. Nothing in these terms limits your statutory consumer rights.']]},refund:{title:'Refund Policy',intro:'We want refunds to be simple and fair. This policy explains when and how they work.',sections:[['Damaged or wrong items','Contact us within 48 hours of delivery with photographs. We will arrange a replacement or a full refund.'],['Order cancelled by us','If we cancel your order, any amount collected is refunded in full to the original payment method.'],['Cash on delivery','For cash on delivery orders, a refund is processed by our team and settled to your account within 5-7 working days of approval.'],['Online payments','Refunds go back to the original payment method and may take 5-7 working days to appear, depending on your bank or provider.'],['Non-refundable cases','Change-of-mind returns are not accepted on opened stationery, unless the product is faulty or incorrect.']]}};
export function LegalPage({kind}){
  const doc=LEGAL[kind];
  if(!doc)return <div className="empty"><h1>Page not found</h1><Link className="btn" to="/">Back to home</Link></div>;
  return <><div className="pagehead"><small>OM STATIONARY</small><h1>{doc.title}</h1><p>{doc.intro}</p></div>
  <section className="content-prose">{doc.sections.map(([h,p])=><div key={h}><h2>{h}</h2><p>{p}</p></div>)}<p className="muted">Last updated 1 September 2026. OM Stationary, {OM_CONTACT.address}.</p></section></>;
}
