import React, { useEffect, useState, useCallback } from 'react';
import { Outlet, Link } from 'react-router-dom';
import { Search, ShoppingCart, User, MapPin, Heart, Bell, ShieldAlert } from 'lucide-react';
import { apiFetch, clearSession, mapServerCart, readSession } from '../../session.js';
import { useCatalog, useCategories } from '../../hooks/useCatalog.js';
import { useNotifications } from '../../hooks/useNotifications.js';
import { FooterMap } from './FooterMap.jsx';

export const AppShellContext=React.createContext(null);

export function AppShell(){const catalog=useCatalog();const navCategories=useCategories();const [user,setUser]=useState(()=>readSession()?.user||null),[cartReady,setCartReady]=useState(()=>!readSession()?.user);const notifications=useNotifications(user);
 // Wishlist is owned by SQL Server. localStorage is only a cache so the header can render
 // instantly; the server is the source of truth and is re-synced on every login/user change.
 const [wishlist,setWishlist]=useState(()=>{try{const saved=JSON.parse(localStorage.getItem('omwishlist')||'[]');return Array.isArray(saved)?saved:[]}catch{return[]}});
 const [wishlistError,setWishlistError]=useState('');
 const [wishlistLoading,setWishlistLoading]=useState(false);
 const syncWishlistFromServer=useCallback(async()=>{setWishlistLoading(true);try{const r=await apiFetch('/api/wishlist');if(r.status===401){setWishlist([]);setWishlistError('');return}if(!r.ok)throw new Error('Wishlist could not be loaded.');const rows=await r.json();const ids=(Array.isArray(rows)?rows:[]).map(x=>x.productId);setWishlist(ids);setWishlistError('');try{localStorage.setItem('omwishlist',JSON.stringify(ids))}catch{}}catch(e){setWishlistError(e.message||'Wishlist could not be loaded.')}finally{setWishlistLoading(false)}},[]);
 useEffect(()=>{if(user?.role==='Customer'){syncWishlistFromServer()}else{setWishlist([]);try{localStorage.removeItem('omwishlist')}catch{}}},[user?.id,user?.role,syncWishlistFromServer]);
 const toggleWishlist=useCallback(async id=>{const saving=!wishlist.includes(id);const previous=wishlist;setWishlist(saving?[...wishlist,id]:wishlist.filter(x=>x!==id));try{localStorage.setItem('omwishlist',JSON.stringify(saving?[...previous,id]:previous.filter(x=>x!==id)))}catch{}
   if(user?.role!=='Customer')return; // guests keep a device-local list until they sign in
   try{const r=await apiFetch('/api/wishlist/'+encodeURIComponent(id),{method:saving?'POST':'DELETE'});if(r.status===401){syncWishlistFromServer();return}if(!r.ok)throw new Error('Wishlist could not be updated.');setWishlistError('');await syncWishlistFromServer()}catch(e){setWishlist(saving?previous.filter(x=>x!==id):[...previous,id]);try{localStorage.setItem('omwishlist',JSON.stringify(previous))}catch{}setWishlistError(e.message||'Wishlist could not be updated.')}},[wishlist,user?.role,syncWishlistFromServer]);
 const [cart,setCart]=useState(()=>{try{const saved=JSON.parse(localStorage.getItem('omcart')||'[]');return Array.isArray(saved)?saved:[]}catch{return[]}}); useEffect(()=>{try{localStorage.setItem('omcart',JSON.stringify(cart))}catch(e){console.warn('Cart could not be saved locally',e)}},[cart]);useEffect(()=>{if(!user){setCartReady(true);return}let alive=true;setCartReady(false);apiFetch('/api/cart').then(async r=>{if(!r.ok)throw new Error('cart');const data=await r.json();if(alive)setCart(mapServerCart(data.items))}).catch(()=>{if(alive)setCartReady(false)}).finally(()=>{});return()=>{alive=false}},[user?.id]);useEffect(()=>{if(!user||!cartReady)return;const timer=setTimeout(()=>apiFetch('/api/cart',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({items:cart.map(i=>({productId:i.id,quantity:i.q}))})}).catch(()=>{}),300);return()=>clearTimeout(timer)},[cart,user?.id,cartReady]);const onAuth=(nextUser,serverCart)=>{setUser(nextUser);setCart(serverCart);setCartReady(true)};const onLogout=async()=>{const session=readSession();try{if(session?.refreshToken)await apiFetch('/api/auth/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refreshToken:session.refreshToken})})}catch{}clearSession();sessionStorage.removeItem('omadminkey');setUser(null);setCart([]);setCartReady(true);setWishlist([]);try{localStorage.removeItem('omwishlist')}catch{}};
const add=p=>setCart(c=>{const x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,q:Math.min(99,i.q+1)}:i):[...c,{...p,q:1}]});
 // Adds an exact quantity in one state update, so the header count and every total move together.
 const addN=(p,n)=>{const qty=Math.max(1,Math.min(99,Math.round(Number(n)||1)));setCart(c=>{const x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,q:Math.min(99,i.q+qty)}:i):[...c,{...p,q:Math.min(99,qty)}]})};
 const change=(id,d)=>setCart(c=>c.map(i=>i.id===id?{...i,q:Math.max(0,i.q+d)}:i).filter(i=>i.q));
 const remove=(id)=>setCart(c=>c.filter(i=>i.id!==id));
return <AppShellContext.Provider value={{catalog,navCategories,user,notifications,wishlist,wishlistError,wishlistLoading,syncWishlistFromServer,toggleWishlist,cart,add,addN,change,remove,clearCart:()=>setCart([]),onAuth,onLogout}}><><header><div className="top"><Link className="logo" to="/"><span>OM</span> STATIONARY<small>Your Learning & Office Partner</small></Link><form className="search" action="/search"><Search size={20}/><input name="q" list="product-suggestions" placeholder="What are you looking for today?"/><datalist id="product-suggestions">{catalog.products.map(p=><option key={p.id} value={p.name}/>)}<option value="A4 Paper"/><option value="Notebook"/><option value="Office supplies"/></datalist><button aria-label="Search"><Search size={18}/></button></form><div className="deliver"><MapPin size={20}/><div><small>Fulfillment</small><b>Check availability</b></div></div><Link to="/orders" className="headlink">Orders</Link><Link to="/wishlist" className="headlink" aria-label="Wishlist"><Heart/><span className="badge">{wishlist.length}</span></Link><Link to="/notifications" className="headlink" aria-label="Notifications"><Bell/><span className="badge">{notifications.unread}</span></Link><Link to="/cart" className="headlink"><ShoppingCart/> <b>{cart.reduce((s,i)=>s+i.q,0)}</b></Link><Link to="/account" className="headlink"><User/></Link>{user?.role==='Admin'&&<Link to="/admin" className="admin-top-button"><ShieldAlert size={17}/> Admin</Link>}</div><div className="tech-ribbon"><div className="tech-ribbon-copy"><strong>Complete E-Commerce Website <span>+ WhatsApp Notification System</span></strong><small>Modern 3D UI&nbsp; | &nbsp;Customer Website&nbsp; | &nbsp;Admin Panel&nbsp; | &nbsp;Real-time Order Updates&nbsp; | &nbsp;Secure &amp; Scalable</small></div><div className="tech-ribbon-stack" aria-label="Store technology"><span>React + Vite</span><span>ASP.NET Core 10</span><span>SQL Server</span><span>WhatsApp API</span></div></div><nav>{[...new Set([...navCategories,...catalog.products.map(p=>p.cat)])].map(c=><Link key={c} to={'/search?cat='+encodeURIComponent(c)}>{c}</Link>)}</nav></header><main><Outlet/></main><FooterMap/></></AppShellContext.Provider>}
