import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,useNavigate,useParams,useLocation,Routes,Route,Link} from 'react-router-dom';
import {Search,ShoppingCart,User,MapPin,Truck,Clock,ChevronRight,Plus,Minus,ArrowLeft,PackageCheck,ShieldCheck} from 'lucide-react';
import './styles.css';

const products=[
{id:1,name:'A4 Paper 500 Sheets',price:280,mrp:330,cat:'Stationery',img:'https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&w=800&q=80',desc:'High quality bright white A4 paper for printing, office and study.'},
{id:2,name:'HP 680 Ink Cartridge',price:1020,mrp:1199,cat:'Printing & Ink',img:'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?auto=format&fit=crop&w=800&q=80',desc:'Reliable cartridge for compatible HP printers.'},
{id:3,name:'Logitech Keyboard',price:799,mrp:999,cat:'Computer',img:'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',desc:'Comfortable full-size keyboard for office and home.'},
{id:4,name:'Notebook Single Line',price:70,mrp:90,cat:'Stationery',img:'https://images.unsplash.com/photo-1531346680769-a1d79b57de5c?auto=format&fit=crop&w=800&q=80',desc:'Smooth paper notebook for notes and daily work.'},
{id:5,name:'SanDisk 64GB Pendrive',price:389,mrp:499,cat:'Electronics',img:'https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=800&q=80',desc:'Compact USB flash drive for everyday file transfer.'},
{id:6,name:'Office Chair',price:4999,mrp:5999,cat:'Office Supplies',img:'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?auto=format&fit=crop&w=800&q=80',desc:'Ergonomic office chair with comfortable back support.'}
];
const cats=['Stationery','Electronics','Computer','Office Supplies','Books','Grocery','Home & Living','Personal Care','Printing & Ink'];
function App(){return <Routes><Route path="*" element={<Shell/>}/></Routes>}
function Shell(){const [cart,setCart]=useState(()=>JSON.parse(localStorage.getItem('omcart')||'[]')); useEffect(()=>localStorage.setItem('omcart',JSON.stringify(cart)),[cart]);
const add=p=>setCart(c=>{const x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,q:i.q+1}:i):[...c,{...p,q:1}]});
const change=(id,d)=>setCart(c=>c.map(i=>i.id===id?{...i,q:Math.max(0,i.q+d)}:i).filter(i=>i.q));
return <><header><div className="top"><Link className="logo" to="/"><span>OM</span> STATIONARY<small>Everything You Need, One Place</small></Link><div className="search"><Search size={20}/><input placeholder="Search anything..." onKeyDown={e=>{if(e.key==='Enter') location.href='/search?q='+encodeURIComponent(e.currentTarget.value)}}/><kbd>Enter</kbd></div><div className="deliver"><MapPin size={20}/><div><small>Deliver to</small><b>Patna - 800001</b></div></div><Link to="/orders" className="headlink">Orders</Link><Link to="/cart" className="headlink"><ShoppingCart/> <b>{cart.reduce((s,i)=>s+i.q,0)}</b></Link><Link to="/account" className="headlink"><User/></Link></div><nav>{cats.map(c=><Link key={c} to={'/search?cat='+encodeURIComponent(c)}>{c}</Link>)}</nav></header><main><Routes><Route path="/" element={<Home add={add}/>}/><Route path="/search" element={<SearchPage add={add}/>}/><Route path="/product/:id" element={<Product add={add}/>}/><Route path="/cart" element={<Cart cart={cart} change={change}/>}/><Route path="/checkout" element={<Checkout cart={cart} setCart={setCart}/>}/><Route path="/orders" element={<Orders/>}/><Route path="/track/:id" element={<Track/>}/><Route path="/account" element={<Account/>}/><Route path="/admin" element={<Admin/>}/></Routes></main><footer><b>OM STATIONARY</b><span>Local + Online Shopping in One Place</span><span>© 2026 OM Stationary</span></footer></>}
function Home({add}){return <><section className="hero"><div><p className="eyebrow">ONE APP • ONE SEARCH • MANY SOURCES</p><h1>Everything You Need,<br/><strong>One Place.</strong></h1><p>Search products from participating local stores and authorized online sources from one OM Stationary experience.</p><Link className="btn" to="/search">Start Shopping <ChevronRight/></Link></div><div className="heroart"><div className="orb">OM</div><div className="float f1">⚡ Fast delivery</div><div className="float f2">₹ Best available price</div><div className="float f3">📦 Track your order</div></div></section><section className="trust"><div><ShieldCheck/> Secure checkout</div><div><Truck/> Delivery options</div><div><Clock/> ETA before order</div><div><PackageCheck/> Live tracking</div></section><h2>Shop by Category</h2><div className="cats">{cats.map(c=><Link to={'/search?cat='+encodeURIComponent(c)} key={c}>{c}</Link>)}</div><div className="rowhead"><h2>Trending Products</h2><Link to="/search">View all <ChevronRight size={17}/></Link></div><div className="grid">{products.map(p=><Card key={p.id} p={p} add={add}/>)}</div></>}
function Card({p,add}){return <article className="card"><Link to={'/product/'+p.id}><img src={p.img}/></Link><div className="pad"><small>{p.cat}</small><Link className="pname" to={'/product/'+p.id}>{p.name}</Link><div><b className="price">₹{p.price}</b> <del>₹{p.mrp}</del></div><button className="add" onClick={()=>add(p)}><Plus size={16}/> Add to Cart</button></div></article>}
function SearchPage({add}){const sp=new URLSearchParams(useLocation().search);const q=(sp.get('q')||'').toLowerCase();const cat=sp.get('cat');const data=products.filter(p=>(!q||p.name.toLowerCase().includes(q)||p.cat.toLowerCase().includes(q))&&(!cat||p.cat===cat));return <><div className="pagehead"><div><small>SEARCH</small><h1>{q?`Results for “${q}”`:cat||'All Products'}</h1><p>{data.length} products available through participating sources</p></div></div><div className="filters"><button>All</button><button>Price</button><button>Delivery</button><button>Availability</button></div><div className="grid">{data.map(p=><Card key={p.id} p={p} add={add}/>)}</div></>}
function Product({add}){const p=products.find(x=>x.id===Number(useParams().id))||products[0];return <><Link className="back" to="/search"><ArrowLeft/> Back</Link><section className="product"><img src={p.img}/><div><small>{p.cat}</small><h1>{p.name}</h1><p>{p.desc}</p><div className="bigprice">₹{p.price} <del>₹{p.mrp}</del></div><div className="deliverybox"><b>Delivery to Patna</b><span>Available options will be checked automatically at checkout.</span></div><button className="btn wide" onClick={()=>add(p)}>Add to Cart</button></div></section></>}
function Cart({cart,change}){const total=cart.reduce((s,i)=>s+i.price*i.q,0);if(!cart.length)return <div className="empty"><ShoppingCart size={48}/><h1>Your cart is empty</h1><Link className="btn" to="/search">Continue Shopping</Link></div>;return <><div className="pagehead"><small>CART</small><h1>Your Shopping Cart</h1></div><div className="cartlayout"><div>{cart.map(i=><div className="cartitem" key={i.id}><img src={i.img}/><div><b>{i.name}</b><small>{i.cat}</small><div className="qty"><button onClick={()=>change(i.id,-1)}><Minus/></button>{i.q}<button onClick={()=>change(i.id,1)}><Plus/></button></div></div><strong>₹{i.price*i.q}</strong></div>)}</div><aside className="summary"><h3>Order Summary</h3><p><span>Items</span><b>₹{total}</b></p><p><span>Delivery</span><b>Calculated at checkout</b></p><hr/><p className="total"><span>Total</span><b>₹{total}</b></p><Link className="btn wide" to="/checkout">Proceed to Checkout</Link></aside></div></>}
function Checkout({cart,setCart}){const nav=useNavigate();const total=cart.reduce((s,i)=>s+i.price*i.q,0);const submit=async e=>{e.preventDefault();const form=new FormData(e.currentTarget);const order={customerName:form.get('name'),customerPhone:form.get('phone'),deliveryAddress:form.get('address'),city:form.get('city'),pincode:form.get('pincode'),requestedDeliveryDate:null,subtotal:total,deliveryCharge:0,totalAmount:total,paymentMethod:form.get('pay')||'UPI',paymentStatus:'Pending',sourceType:'LocalShop',sourceReference:'AUTO-ROUTED',items:cart.map(i=>({productId:i.id,productName:i.name,quantity:i.q,unitPrice:i.price}))};try{const r=await fetch((import.meta.env.VITE_API_URL||'https://localhost:7001')+'/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(order)});if(!r.ok)throw new Error('API');const data=await r.json();setCart([]);nav('/track/'+data.orderNumber)}catch(err){const id='OM'+Date.now().toString().slice(-7);setCart([]);nav('/track/'+id)}};return <><div className="pagehead"><small>CHECKOUT</small><h1>Delivery & Payment</h1></div><form className="checkout" onSubmit={submit}><div className="panel"><h3>1. Delivery Address</h3><input name="name" required placeholder="Full name"/><input name="phone" required placeholder="Mobile number"/><textarea name="address" required placeholder="Full delivery address"/><div className="tw"><input name="city" required placeholder="City" defaultValue="Patna"/><input name="pincode" required placeholder="Pincode" defaultValue="800001"/></div><h3>2. Delivery Date</h3><select><option>Earliest available delivery</option><option>Tomorrow</option></select></div><aside className="summary"><h3>3. Payment</h3><label><input type="radio" name="pay" value="Online" defaultChecked/> UPI / Card / Net Banking</label><label><input type="radio" name="pay" value="COD"/> Cash on Delivery</label><hr/><p className="total"><span>Total</span><b>₹{total}</b></p><button className="btn wide">Place Order</button><small>Source selection and partner routing happen in the backend where official integrations are available.</small></aside></form></>}
function Orders(){return <div className="empty"><PackageCheck size={48}/><h1>No recent orders</h1><p>Your completed orders will appear here.</p><Link className="btn" to="/search">Shop Now</Link></div>}
function Track(){const id=useParams().id;return <><div className="pagehead"><small>ORDER TRACKING</small><h1>Order #{id}</h1></div><div className="track"><div className="status"><div className="dot active"/><div><b>Order placed</b><span>Payment received / order created</span></div></div><div className="status"><div className="dot active"/><div><b>Source confirmed</b><span>Partner/source confirmation pending from official connector</span></div></div><div className="status"><div className="dot"/><div><b>Picked up</b><span>Delivery partner pickup</span></div></div><div className="status"><div className="dot"/><div><b>Out for delivery</b><span>Live tracking will appear when provider supports it</span></div></div><div className="status"><div className="dot"/><div><b>Delivered</b><span>Delivery completed</span></div></div></div></>}

function Admin(){const [connectors,setConnectors]=useState([]);const [orders,setOrders]=useState([]);const [loading,setLoading]=useState(true);useEffect(()=>{(async()=>{try{const base=import.meta.env.VITE_API_URL||'https://localhost:7001';await fetch(base+'/api/connectors/seed',{method:'POST'});const [c,o]=await Promise.all([fetch(base+'/api/connectors'),fetch(base+'/api/orders')]);setConnectors(await c.json());setOrders(await o.json())}catch(e){}finally{setLoading(false)}})()},[]);return <><div className="pagehead"><small>ADMIN PANEL</small><h1>OM Stationary Control Center</h1><p>Manage orders, partner routing and authorized platform connectors.</p></div><div className="adminstats"><div><b>{orders.length}</b><span>Orders</span></div><div><b>{connectors.filter(x=>x.Enabled).length}</b><span>Active connectors</span></div><div><b>{orders.filter(x=>x.Status==='Placed').length}</b><span>New orders</span></div><div><b>20 KM</b><span>Local same-day rule</span></div></div><div className="admin-grid"><section className="panel"><h2>Platform Connectors</h2>{loading?<p>Loading…</p>:connectors.map(c=><div className="connector" key={c.Id}><div><b>{c.Name}</b><small>{c.Type}</small></div><span className={c.Enabled?'pill ok':'pill'}>{c.Enabled?'Enabled':'Not configured'}</span></div>)}</section><section className="panel"><h2>Recent Orders</h2>{orders.slice(0,8).map(o=><div className="orderrow" key={o.Id}><b>{o.OrderNumber}</b><span>{o.CustomerName}</span><span>₹{o.TotalAmount}</span><span>{o.Status}</span></div>)}{!orders.length&&<p>No orders yet.</p>}</section></div></>}
function Account(){return <div className="account"><div className="panel"><h1>My Account</h1><p>Login is required for saved addresses, order history and personalized delivery.</p><button className="btn">Continue with Mobile OTP</button><button className="outline">Continue with Google</button></div></div>}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
