import { useContext } from 'react';
import { AppShellContext } from './components/layout/AppShell.jsx';
import { AccountPage } from './pages/customer/AccountPage.jsx';
import { AboutPage } from './pages/customer/AboutPage.jsx';
import { CartPage } from './pages/customer/CartPage.jsx';
import { CheckoutPage } from './pages/customer/CheckoutPage.jsx';
import { ContactPage } from './pages/customer/ContactPage.jsx';
import { HelpPage } from './pages/customer/HelpPage.jsx';
import { HomePage } from './pages/customer/HomePage.jsx';
import { InvoicePage } from './pages/customer/InvoicePage.jsx';
import { PrivacyPage } from './pages/customer/PrivacyPage.jsx';
import { TermsPage } from './pages/customer/TermsPage.jsx';
import { RefundPolicyPage } from './pages/customer/RefundPolicyPage.jsx';
import { LoginPage } from './pages/customer/LoginPage.jsx';
import { NotificationsPage } from './pages/customer/NotificationsPage.jsx';
import { OrderSuccessPage } from './pages/customer/OrderSuccessPage.jsx';
import { OrdersPage } from './pages/customer/OrdersPage.jsx';
import { PaymentPage } from './pages/customer/PaymentPage.jsx';
import { ProductDetailPage } from './pages/customer/ProductDetailPage.jsx';
import { ProductListingPage } from './pages/customer/ProductListingPage.jsx';
import { RegisterPage } from './pages/customer/RegisterPage.jsx';
import { TrackOrderPage } from './pages/customer/TrackOrderPage.jsx';
import { WishlistPage } from './pages/customer/WishlistPage.jsx';
import { PartnerDashboardPage } from './pages/partner/PartnerDashboardPage.jsx';
import { PartnerInventoryPage } from './pages/partner/PartnerInventoryPage.jsx';
import { PartnerOrdersPage } from './pages/partner/PartnerOrdersPage.jsx';
import { PartnerProfilePage } from './pages/partner/PartnerProfilePage.jsx';
import { PartnerProductsPage } from './pages/partner/PartnerProductsPage.jsx';
import { PartnerOrderDetailPage } from './pages/partner/PartnerOrderDetailPage.jsx';
import { DeliveryDashboardPage } from './pages/delivery/DeliveryDashboardPage.jsx';
import { AssignedDeliveriesPage } from './pages/delivery/AssignedDeliveriesPage.jsx';
import { DeliveryDetailPage } from './pages/delivery/DeliveryDetailPage.jsx';
import { DeliveryHistoryPage } from './pages/delivery/DeliveryHistoryPage.jsx';
import { DeliveryProfilePage } from './pages/delivery/DeliveryProfilePage.jsx';
import { AdminDashboardPage } from './pages/admin/AdminDashboardPage.jsx';
import { AdminOrdersPage } from './pages/admin/AdminOrdersPage.jsx';
import { AdminOrderDetailPage } from './pages/admin/AdminOrderDetailPage.jsx';
import { AdminProductsPage } from './pages/admin/AdminProductsPage.jsx';
import { AdminProductFormPage } from './pages/admin/AdminProductFormPage.jsx';
import { AdminCategoriesPage } from './pages/admin/AdminCategoriesPage.jsx';
import { AdminInventoryPage } from './pages/admin/AdminInventoryPage.jsx';
import { AdminCustomersPage } from './pages/admin/AdminCustomersPage.jsx';
import { AdminPaymentsPage } from './pages/admin/AdminPaymentsPage.jsx';
import { AdminCouponsPage } from './pages/admin/AdminCouponsPage.jsx';
import { AdminDeliveryPage } from './pages/admin/AdminDeliveryPage.jsx';
import { AdminInvoicesPage } from './pages/admin/AdminInvoicesPage.jsx';
import { AdminPartnerShopsPage } from './pages/admin/AdminPartnerShopsPage.jsx';
import { AdminReportsPage } from './pages/admin/AdminReportsPage.jsx';
import { AdminNotificationsPage } from './pages/admin/AdminNotificationsPage.jsx';
import { AdminWhatsAppPage } from './pages/admin/AdminWhatsAppPage.jsx';
import { AdminSettingsPage } from './pages/admin/AdminSettingsPage.jsx';
import { AdminAuditLogPage } from './pages/admin/AdminAuditLogPage.jsx';

export function RouteView({ page }) {
  const state = useContext(AppShellContext);
  const customerProps = {
    add: state.add, addN: state.addN, catalog: state.catalog,
    categories: state.navCategories, wishlist: state.wishlist,
    toggleWishlist: state.toggleWishlist
  };
  const adminProps = { user: state.user, onLogout: state.onLogout };
  switch (page) {
    case 'home': return <HomePage {...customerProps} />;
    case 'search': return <ProductListingPage {...customerProps} />;
    case 'product': return <ProductDetailPage {...customerProps} />;
    case 'cart': return <CartPage cart={state.cart} change={state.change} remove={state.remove} addN={state.addN} />;
    case 'wishlist': return <WishlistPage catalog={state.catalog} wishlist={state.wishlist} add={state.add} addN={state.addN} toggleWishlist={state.toggleWishlist} user={state.user} error={state.wishlistError} loading={state.wishlistLoading} reload={state.syncWishlistFromServer} />;
    case 'checkout': return <CheckoutPage cart={state.cart} user={state.user} onCartCleared={state.clearCart} />;
    case 'payment': return <PaymentPage />;
    case 'order-success': return <OrderSuccessPage />;
    case 'invoice': return <InvoicePage />;
    case 'orders': return <OrdersPage user={state.user} />;
    case 'track': return <TrackOrderPage />;
    case 'login': return <LoginPage onAuth={state.onAuth} />;
    case 'register': return <RegisterPage onAuth={state.onAuth} />;
    case 'account': return <AccountPage user={state.user} onLogout={state.onLogout} />;
    case 'notifications': return <NotificationsPage />;
    case 'about': return <AboutPage />;
    case 'contact': return <ContactPage />;
    case 'help': return <HelpPage />;
    case 'privacy': return <PrivacyPage />;
    case 'terms': return <TermsPage />;
    case 'refund': return <RefundPolicyPage />;
    case 'admin-home': return <AdminDashboardPage {...adminProps} />;
    case 'admin-orders': return <AdminOrdersPage {...adminProps} />;
    case 'admin-order': return <AdminOrderDetailPage {...adminProps} />;
    case 'admin-products': return <AdminProductsPage {...adminProps} />;
    case 'admin-product-form': return <AdminProductFormPage {...adminProps} />;
    case 'admin-categories': return <AdminCategoriesPage {...adminProps} />;
    case 'admin-inventory': return <AdminInventoryPage {...adminProps} />;
    case 'admin-customers': return <AdminCustomersPage {...adminProps} />;
    case 'admin-payments': return <AdminPaymentsPage {...adminProps} />;
    case 'admin-coupons': return <AdminCouponsPage {...adminProps} />;
    case 'admin-delivery': return <AdminDeliveryPage {...adminProps} />;
    case 'admin-invoices': return <AdminInvoicesPage {...adminProps} />;
    case 'admin-partners': return <AdminPartnerShopsPage {...adminProps} />;
    case 'admin-reports': return <AdminReportsPage {...adminProps} />;
    case 'admin-notifications': return <AdminNotificationsPage {...adminProps} />;
    case 'admin-whatsapp': return <AdminWhatsAppPage {...adminProps} />;
    case 'admin-settings': return <AdminSettingsPage {...adminProps} />;
    case 'admin-audit': return <AdminAuditLogPage {...adminProps} />;
    case 'partner-home': return <PartnerDashboardPage />;
    case 'partner-inventory': return <PartnerInventoryPage />;
    case 'partner-orders': return <PartnerOrdersPage />;
    case 'partner-profile': return <PartnerProfilePage />;
    case 'partner-products': return <PartnerProductsPage />;
    case 'partner-order': return <PartnerOrderDetailPage />;
    case 'delivery-home': return <DeliveryDashboardPage />;
    case 'delivery-assigned': return <AssignedDeliveriesPage />;
    case 'delivery-detail': return <DeliveryDetailPage />;
    case 'delivery-history': return <DeliveryHistoryPage />;
    case 'delivery-profile': return <DeliveryProfilePage />;
    default: return null;
  }
}
