import { useCallback, useEffect, useState } from 'react';
import { AdminLayout } from '../../components/admin/AdminLayout.jsx';
import { AdminDataTable } from '../../components/admin/AdminDataTable.jsx';
import { Modal } from '../../components/common/Modal.jsx';
import { adminHeaders, assignDeliveryPartner, createDeliveryPartner, listAllAssignments, listDeliveryPartners } from '../../services/adminService.js';
import { readSession } from '../../services/session.js';

const emptyPartner = { name: '', mobile: '', email: '', vehicleType: '', vehicleNumber: '', password: '' };
export function AdminDeliveryPage({ user, onLogout }) {
  const headers = adminHeaders(readSession()); const [partners, setPartners] = useState([]); const [assignments, setAssignments] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [createOpen, setCreateOpen] = useState(false); const [partner, setPartner] = useState(emptyPartner); const [selection, setSelection] = useState({});
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [p, a] = await Promise.all([listDeliveryPartners(headers), listAllAssignments(headers)]); setPartners(p); setAssignments(a); } catch (e) { setError(e.message); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const create = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { const r = await createDeliveryPartner(partner, headers); if (!r.ok) throw new Error((await r.json().catch(() => ({}))).detail || 'Could not create delivery partner.'); setCreateOpen(false); setPartner(emptyPartner); await load(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const assign = async (row) => { const value = selection[row.id]; if (!available.some((p) => String(p.id) === String(value))) { setError('Choose an available delivery partner.'); return; } setBusy(true); setError(''); try { const r = await assignDeliveryPartner(row.orderId, value, row.trackingCode || '', headers); if (!r.ok) throw new Error((await r.json().catch(() => ({}))).detail || 'Could not assign delivery.'); await load(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const available = partners.filter((p) => p.status === 'Active' && p.isAvailable);
  return <AdminLayout user={user} onLogout={onLogout}><div className="pagehead"><small>ADMIN PANEL</small><h1>Delivery management</h1><p>Manage delivery partners and server-recorded assignments.</p><button className="btn" onClick={() => setCreateOpen(true)}>Create delivery partner</button></div>{error && <p role="alert" className="form-error">{error}</p>}
    <h2>Delivery partners</h2><AdminDataTable loading={loading} rows={partners} total={partners.length} columns={[{ key: 'name', label: 'Name' }, { key: 'contact', label: 'Contact' }, { key: 'vehicle', label: 'Vehicle' }, { key: 'status', label: 'Status' }, { key: 'available', label: 'Availability' }]} empty="No delivery partners are registered." renderRow={(p) => <tr key={p.id}><td>{p.name}</td><td>{p.mobile}<small>{p.email}</small></td><td>{p.vehicleType} {p.vehicleNumber}</td><td>{p.status}</td><td>{p.isAvailable ? 'Available' : 'Assigned'}</td></tr>} />
    <h2>Assignments</h2><AdminDataTable loading={loading} rows={assignments} total={assignments.length} columns={[{ key: 'order', label: 'Order' }, { key: 'partner', label: 'Partner' }, { key: 'tracking', label: 'Tracking' }, { key: 'status', label: 'Status' }, { key: 'charge', label: 'Charge' }, { key: 'assign', label: 'Assign / reassign' }]} empty="No delivery assignments exist." renderRow={(a) => <tr key={a.id}><td>{a.orderNumber}</td><td>{a.partnerName || '-'}</td><td>{a.trackingCode || '-'}</td><td>{a.status}</td><td>{a.charge}</td><td><div className="admin-filter-row"><select aria-label={`Partner for ${a.orderNumber}`} value={selection[a.id] ?? (available.some((p) => String(p.id) === String(a.deliveryPartnerId)) ? a.deliveryPartnerId : '')} onChange={(e) => setSelection((old) => ({ ...old, [a.id]: e.target.value }))}><option value="">Select available partner</option>{available.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="outline" disabled={busy || !available.length || !available.some((p) => String(p.id) === String(selection[a.id] ?? a.deliveryPartnerId))} onClick={() => assign(a)}>Assign</button></div></td></tr>} />
    <Modal open={createOpen} onClose={() => !busy && setCreateOpen(false)} title="Create delivery partner"><form className="admin-form" onSubmit={create}>{[['name','Name'],['mobile','Mobile'],['email','Email'],['vehicleType','Vehicle type'],['vehicleNumber','Vehicle number'],['password','Temporary password']].map(([key,label]) => <label key={key}>{label}<input name={key} type={key === 'password' ? 'password' : key === 'email' ? 'email' : 'text'} required value={partner[key]} onChange={(e) => setPartner((p) => ({ ...p, [key]: e.target.value }))} /></label>)}<button className="btn" disabled={busy}>{busy ? 'Creating...' : 'Create partner'}</button></form></Modal>
  </AdminLayout>;
}
