import { useEffect, useState } from 'react';
import { AdminLayout } from '../../components/admin/AdminLayout.jsx';
import { WhatsAppSettingsForm } from '../../components/whatsapp/WhatsAppSettingsForm.jsx';
import { WhatsAppLogsTable } from '../../components/whatsapp/WhatsAppLogsTable.jsx';
import { WhatsAppTestButton } from '../../components/whatsapp/WhatsAppTestButton.jsx';
import { getWhatsAppConfig, saveWhatsAppSettings, sendWhatsAppTest, retryWhatsAppNotification } from '../../services/whatsappService.js';
import { adminHeaders } from '../../services/adminService.js';
import { readSession } from '../../services/session.js';

export function AdminWhatsAppPage({user,onLogout}) { const [config,setConfig]=useState(null); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const headers=adminHeaders(readSession()); const load=()=>getWhatsAppConfig(headers).then(setConfig).catch(e=>setError(e.message)); useEffect(()=>{load();},[]); const patch=async update=>{setBusy(true);setError('');try{await saveWhatsAppSettings(update,headers);await load();}catch(e){setError(e.message);}finally{setBusy(false);}}; const test=async()=>{setBusy(true);try{const r=await sendWhatsAppTest(headers);if(!r.ok)throw new Error((await r.json().catch(()=>({}))).detail||'WhatsApp test failed.');await load();}catch(e){setError(e.message);}finally{setBusy(false);}}; const retry=async id=>{setBusy(true);try{const r=await retryWhatsAppNotification(id,headers);if(!r.ok)throw new Error('Could not retry notification.');await load();}catch(e){setError(e.message);}finally{setBusy(false);}}; return <AdminLayout user={user} onLogout={onLogout}><div className="pagehead"><small>ADMIN PANEL</small><h1>WhatsApp</h1><p>Manage server-configured notifications and inspect delivery attempts.</p></div>{error&&<p role="alert" className="form-error">{error}</p>}<WhatsAppSettingsForm config={config} busy={busy} onToggleEnabled={enabled=>patch({enabled})} onToggleEvent={(event,enabled)=>patch({events:{[event]:enabled}})}/><WhatsAppTestButton busy={busy} configured={!!config?.configuration?.enabled} onSend={test}/>{config&&<WhatsAppLogsTable logs={config.log||[]} busy={busy} onRetry={retry}/>}</AdminLayout>; }
